// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByS60vp7_RTUXyVZZ7sFznxb-xz2e75fA',
    appId: '1:559618073226:web:c0b48bca9baf4edfd90373',
    messagingSenderId: '559618073226',
    projectId: 'real-estate-c4df0',
    authDomain: 'real-estate-c4df0.firebaseapp.com',
    storageBucket: 'real-estate-c4df0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYebEgx7mJjIHG1q675inCHseEFIJvl3c',
    appId: '1:559618073226:android:b1f39a2737c65810d90373',
    messagingSenderId: '559618073226',
    projectId: 'real-estate-c4df0',
    storageBucket: 'real-estate-c4df0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC45l3bRLPbls3MeCYX7pgV-c-16D6HKaI',
    appId: '1:559618073226:ios:590b7a6837469f43d90373',
    messagingSenderId: '559618073226',
    projectId: 'real-estate-c4df0',
    storageBucket: 'real-estate-c4df0.firebasestorage.app',
    iosBundleId: 'com.example.realEstate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByS60vp7_RTUXyVZZ7sFznxb-xz2e75fA',
    appId: '1:559618073226:web:11a0d68313d21961d90373',
    messagingSenderId: '559618073226',
    projectId: 'real-estate-c4df0',
    authDomain: 'real-estate-c4df0.firebaseapp.com',
    storageBucket: 'real-estate-c4df0.firebasestorage.app',
  );
}
